In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

base_dir = 'C:\\Code\\Github\\States_pupil_analysis\\'
os.chdir(base_dir)  # Change the working directory to the current file directory  

# Import your helper functions
from helper_functions.data_loader import DataLoader  # Import the DataLoader class
from helper_functions.data_analyzer import DataAnalyzer
from helper_functions.data_aligner import DataAligner
from helper_functions.data_pipeline import DataPipeline
from helper_functions.data_plotter import Plotter

In [2]:
# Your datasets list
datasets = [
    ("HA1-00", "2023-06-27", 'V:'),

]

# datasets = [("HA1-00", "2023-06-27", 'V:'),("HA1-00", "2023-06-29", 'V:')]
# Define the base directory for datasets
base_dir = 'C:\\Code\\Github\\States_pupil_analysis\\datasets\\'

# Now run your pipeline
pipeline = DataPipeline()

# Load the data from the datasets list
data_loaders, celltype_info = pipeline.load_data(datasets,load_celltypes=1) 



Loading data for: Animal: HA1-00, Date: 2023-06-27, Server: V:


In [3]:
good_trials_all = []
alignment = {}
alignment['type']  = 'pre'  
for data_loader, (key, info) in zip(data_loaders, celltype_info.items()):
    animalID, date = key
    server_info = info  # This will be the celltype information for the corresponding dataset

    celltypes = celltype_info[animalID, date]['neuron_groups']

    # Load the data using the data loader
    pupil_data = data_loader.load_pupil_data()
    neural_data, good_trials, trial_info, movement_in_imaging, frame_id_events, file_num, velocity_data, imaging = data_loader.load_neural_data(neural_data_type='dff')
    good_trials_all.append(good_trials)
    # latent_states = data_loader.load_latent_states() #could be other things like correct/incorrect or performance metric

    # Align the data
    imaging_frame_lengths = data_loader.load_alignment_data()
    global_frame_ids = data_loader.align_frames_to_session(file_num, frame_id_events, imaging_frame_lengths)

    # Define movement frames by trial
    movement_frames = {}
    
    for trial in range(len(neural_data)):
        if trial in good_trials:
            movement_frames[trial] = {
                'maze_frames': movement_in_imaging[trial]['maze_frames'],
                'reward_frames': movement_in_imaging[trial]['reward_frames'],
                'iti_frames': movement_in_imaging[trial]['iti_frames']
            }
        else:
            movement_frames[trial] = None

    # Initialize the DataAligner with the new parameters
    aligner = DataAligner(neural_data, movement_frames, velocity_data, global_frame_ids, good_trials)

    # Align the data to the desired epoch (e.g., 'maze', 'reward', 'iti', or 'all')
    align_info, alignment_frames, left_padding, right_padding = aligner.find_align_info(imaging, 30, alternative_alignment=False) #neural (mean across cells), pupil, velocity, and neural_all (single cells)
    aligned_imaging, imaging_array, align_info, frames = aligner.align_behavior_data( imaging, align_info, alignment_frames, left_padding, right_padding, 
                       alignment = alignment, cell_ids=None)
    

W:/Connie/Analysis/HA1-00-2023-06-27/HA1-00-2023-06-27final_fit.csv


ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.

In [4]:
imaging_array = [imaging[i]['movement_in_imaging_time'][0][0] for i in good_trials]

In [ ]:
[
trial['turn_frame'][0] - 1 if isinstance(trial['turn_frame'], list) else trial['turn_frame'] - 1
for trial in imaging_array
]

[array([[223]], dtype=uint8),
 array([[221]], dtype=uint8),
 array([[228]], dtype=uint8),
 array([[235]], dtype=uint8),
 array([[357]], dtype=uint16),
 array([[631]], dtype=uint16),
 array([[256]], dtype=uint16),
 array([[282]], dtype=uint16),
 array([[1292]], dtype=uint16),
 array([[691]], dtype=uint16),
 array([[232]], dtype=uint8),
 array([[266]], dtype=uint16),
 array([[237]], dtype=uint8),
 array([[302]], dtype=uint16),
 array([[272]], dtype=uint16),
 array([[293]], dtype=uint16),
 array([[354]], dtype=uint16),
 array([[248]], dtype=uint8),
 array([[245]], dtype=uint8),
 array([[410]], dtype=uint16),
 array([[255]], dtype=uint16),
 array([[251]], dtype=uint8),
 array([[243]], dtype=uint8),
 array([[268]], dtype=uint16),
 array([[241]], dtype=uint8),
 array([[257]], dtype=uint16),
 array([[276]], dtype=uint16),
 array([[288]], dtype=uint16),
 array([[281]], dtype=uint16),
 array([[681]], dtype=uint16),
 array([[244]], dtype=uint8),
 array([[226]], dtype=uint8),
 array([[223]], dtyp

In [14]:
[trial['turn_frame'][0] for trial in imaging_array]

[array([224], dtype=uint8),
 array([222], dtype=uint8),
 array([229], dtype=uint8),
 array([236], dtype=uint8),
 array([358], dtype=uint16),
 array([632], dtype=uint16),
 array([257], dtype=uint16),
 array([283], dtype=uint16),
 array([1293], dtype=uint16),
 array([692], dtype=uint16),
 array([233], dtype=uint8),
 array([267], dtype=uint16),
 array([238], dtype=uint8),
 array([303], dtype=uint16),
 array([273], dtype=uint16),
 array([294], dtype=uint16),
 array([355], dtype=uint16),
 array([249], dtype=uint8),
 array([246], dtype=uint8),
 array([411], dtype=uint16),
 array([256], dtype=uint16),
 array([252], dtype=uint8),
 array([244], dtype=uint8),
 array([269], dtype=uint16),
 array([242], dtype=uint8),
 array([258], dtype=uint16),
 array([277], dtype=uint16),
 array([289], dtype=uint16),
 array([282], dtype=uint16),
 array([682], dtype=uint16),
 array([245], dtype=uint8),
 array([227], dtype=uint8),
 array([224], dtype=uint8),
 array([311], dtype=uint16),
 array([255], dtype=uint8),